import Link from "next/link";
import Image from "next/image";

export default function Chapter02OverviewPage() {
  return (
    <article className="mx-auto max-w-3xl space-y-10">
      <header className="border-b border-slate-200 pb-6">
        <nav
          aria-label="Breadcrumb"
          className="mb-3 flex items-center text-xs text-slate-500 sm:text-sm"
        >
          <Link
            href="/"
            className="transition hover:text-indigo-700 hover:underline"
          >
            Home
          </Link>
          <span className="mx-1">›</span>
          <Link
            href="/chapter-02"
            className="transition hover:text-indigo-700 hover:underline"
          >
            Chapter 02
          </Link>
          <span className="mx-1">›</span>
          <span className="font-medium text-slate-700">
            Object Oriented Principles
          </span>
        </nav>

        <h1 className="text-3xl font-semibold tracking-tight text-slate-900">
          Chapter 02: Object Oriented Principles
        </h1>
        <p className="mt-2 text-sm text-slate-500">
          An overview of the core object-oriented principles in Java: inheritance,
          polymorphism, abstraction, and encapsulation, and how they shape class
          design.
        </p>
      </header>

      <figure className="space-y-2">
        <div className="border border-slate-200 bg-slate-50 p-2">
          <Image
            src="/oop-four-pillars-img-02.png"
            alt="Diagram of the four main object-oriented principles in Java: inheritance, polymorphism, abstraction, and encapsulation"
            width={960}
            height={540}
            className="h-auto w-full"
            priority
          />
        </div>
        <figcaption className="text-center text-xs italic text-slate-500">
          generated by NotebookLM
        </figcaption>
      </figure>

      <section className="space-y-3">
        <h2 className="border-l-4 border-amber-400 pl-3 text-xl font-semibold text-indigo-900">
          Why Object-Oriented Principles Matter
        </h2>
        <p className="text-slate-700">
          Object-Oriented Programming (OOP) organizes software around objects rather
          than just functions. In Java, these principles help us to design reusable,
          maintainable, and secure applications by modeling real-world entities and
          relationships.
        </p>
        <p className="text-slate-700">
          The four main pillars of OOP are inheritance, polymorphism, abstraction,
          and encapsulation. The rest of this chapter explores each of them in
          detail with examples.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="border-l-4 border-amber-400 pl-3 text-xl font-semibold text-indigo-900">
          Inheritance
        </h2>
        <p className="text-slate-700">
          Inheritance allows one class (the subclass) to reuse and extend the
          behavior of another class (the superclass). It represents an
          <strong>"is-a"</strong> relationship between two types.
        </p>
        <ul className="ml-6 list-disc space-y-1.5 text-slate-700">
          <li>Promotes code reuse and reduces duplication.</li>
          <li>Enables hierarchical class structures.</li>
          <li>Implemented in Java using the <code>extends</code> keyword.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="border-l-4 border-amber-400 pl-3 text-xl font-semibold text-indigo-900">
          Polymorphism
        </h2>
        <p className="text-slate-700">
          Polymorphism means "many forms". It allows the same operation to behave
          differently depending on the actual object that receives the call.
        </p>
        <ul className="ml-6 list-disc space-y-1.5 text-slate-700">
          <li>
            <strong>Compile-time polymorphism</strong> via method overloading.
          </li>
          <li>
            <strong>Runtime polymorphism</strong> via method overriding and dynamic
              binding.
          </li>
          <li>Helps design flexible APIs that work with base types.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="border-l-4 border-amber-400 pl-3 text-xl font-semibold text-indigo-900">
          Abstraction
        </h2>
        <p className="text-slate-700">
          Abstraction focuses on exposing only essential features of an object while
          hiding unnecessary details. In Java, this is implemented using abstract
          classes and interfaces.
        </p>
        <ul className="ml-6 list-disc space-y-1.5 text-slate-700">
          <li>Separates what an object does from how it does it.</li>
          <li>Encourages clean, high-level designs.</li>
          <li>Supports plug-and-play implementations via interfaces.</li>
        </ul>
      </section>
      <section className="space-y-3">
        <h2 className="border-l-4 border-amber-400 pl-3 text-xl font-semibold text-indigo-900">
          Encapsulation
        </h2>
        <p className="text-slate-700">
          Encapsulation is the idea of bundling data and methods that operate on
          that data into a single unit (a class), and restricting direct access to
          internal details.
        </p>
        <ul className="ml-6 list-disc space-y-1.5 text-slate-700">
          <li>Achieved using access modifiers like <code>private</code> and getters/setters.</li>
          <li>Protects invariants and improves security.</li>
          <li>Makes it easier to change internal implementation later.</li>
        </ul>
      </section>

      <div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 pt-6">
        <Link
            href="/chapter-02"
            className="inline-flex items-center gap-2 border border-indigo-100 bg-indigo-50 px-4 py-2 text-sm font-medium text-indigo-900 shadow-sm"
          >
            <span className="text-lg">←</span>
            <span>Previous: Chapter 02 Overview</span>
          </Link>
        <Link
            href="/chapter-02/super-sub-class"
            className="inline-flex items-center gap-2 bg-[#1a3c8b] px-4 py-2 text-sm font-medium text-white shadow-md"
          >
            <span>Next: 2.2 Super and Sub Class</span>
            <span className="text-lg">→</span>
          </Link>
      </div>
    </article>
  );
}
