import Link from "next/link";
import Image from "next/image";

export default function ArchitecturePage() {
  return (
    <article className="mx-auto max-w-3xl space-y-10">
      <header className="border-b border-slate-200 pb-6">
        <nav
          aria-label="Breadcrumb"
          className="mb-3 flex items-center text-xs text-slate-500 sm:text-sm"
        >
          <Link
            href="/"
            className="transition hover:text-indigo-700 hover:underline"
          >
            Home
          </Link>
          <span className="mx-1">›</span>
          <Link
            href="/chapter-01"
            className="transition hover:text-indigo-700 hover:underline"
          >
            Chapter 01
          </Link>
          <span className="mx-1">›</span>
          <span className="font-medium text-slate-700">
            1.2 Java Architecture
          </span>
        </nav>

        <h1 className="text-3xl font-semibold tracking-tight text-slate-900">
          1.2 Java Architecture
        </h1>
        <p className="mt-2 text-sm text-slate-500">
          How Java turns your source code into platform-independent bytecode and
          then into machine instructions using the JVM and JRE.
        </p>
      </header>

      {/* Architecture diagram */}
      <figure className="space-y-2">
        <div className="border border-slate-200 bg-slate-50 p-2">
          <Image
            src="/java-architecture.png"
            alt="High-level Java architecture showing source code, compiler, bytecode, JVM and JRE"
            width={960}
            height={540}
            className="h-auto w-full"
            priority
          />
        </div>
        <figcaption className="text-center text-xs italic text-slate-500">
          generated by NotebookLM
        </figcaption>
      </figure>

      {/* Compilation flow */}
      <section className="space-y-3">
        <h2 className="border-l-4 border-amber-400 pl-3 text-xl font-semibold text-indigo-900">
          From Source Code to Bytecode
        </h2>
        <p className="text-slate-700">
          Java follows a two-step compilation model. Instead of compiling
          directly to machine code for one operating system, the compiler first
          produces an intermediate, platform-neutral format called bytecode.
        </p>
        <ul className="ml-6 list-disc space-y-2 text-slate-700">
          <li>
            <span className="font-semibold">Source code:</span> You write Java
            programs in <code>.java</code> files.
          </li>
          <li>
            <span className="font-semibold">Compiler:</span> The Java compiler
            checks your code for errors and translates it into bytecode.
          </li>
          <li>
            <span className="font-semibold">Bytecode:</span> The compiled
            instructions are stored in <code>.class</code> files and are
            understood by the JVM, not directly by the operating system.
          </li>
        </ul>
      </section>

      {/* Execution flow */}
      <section className="space-y-3">
        <h2 className="border-l-4 border-amber-400 pl-3 text-xl font-semibold text-indigo-900">
          Execution: JRE, JVM and JIT
        </h2>
        <p className="text-slate-700">
          Once bytecode is generated, the Java Runtime Environment (JRE)
          provides everything needed to run it on a particular machine.
        </p>
        <div className="space-y-4">
          <div className="rounded border border-slate-200 bg-slate-50 p-4">
            <h3 className="font-semibold text-slate-800">1. Class Loader</h3>
            <p className="text-sm text-slate-700">
              Loads all the required <code>.class</code> files into memory when
              your program starts so that the JVM can use them.
            </p>
          </div>
          <div className="rounded border border-slate-200 bg-slate-50 p-4">
            <h3 className="font-semibold text-slate-800">2. Bytecode Verifier</h3>
            <p className="text-sm text-slate-700">
              Checks the loaded bytecode to ensure it is safe and follows JVM
              rules, preventing illegal memory access or corrupted instructions.
            </p>
          </div>
          <div className="rounded border border-slate-200 bg-slate-50 p-4">
            <h3 className="font-semibold text-slate-800">3. JVM and JIT Compiler</h3>
            <p className="text-sm text-slate-700">
              The Java Virtual Machine (JVM) interprets or compiles bytecode
              into native machine code. The Just-In-Time (JIT) compiler detects
              frequently executed sections and compiles them once for faster
              reuse.
            </p>
          </div>
        </div>
      </section>

      {/* Key takeaway */}
      <section className="border-l-4 border-amber-400 bg-amber-50 px-4 py-3 text-sm text-amber-900">
        Thanks to this architecture, the same compiled Java program can run on
        different operating systems, as long as a compatible JRE is available
        on each machine.
      </section>

      {/* Navigation */}
      <div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 pt-6">
        <Link
          href="/chapter-01/first-program"
          className="inline-flex items-center gap-2 border border-indigo-100 bg-indigo-50 px-4 py-2 text-sm font-medium text-indigo-900 shadow-sm"
        >
          <span className="text-lg">←</span>
          <span>Previous: 1.1 First Program</span>
        </Link>
        <Link
          href="/chapter-01/class-paths"
          className="inline-flex items-center gap-2 bg-[#1a3c8b] px-4 py-2 text-sm font-medium text-white shadow-md"
        >
          <span>Next: 1.3 Class Paths</span>
          <span className="text-lg">→</span>
        </Link>
      </div>
    </article>
  );
}